name: Publish
# Controls when the workflow will run
on:
  # Triggers the workflow on release events
  release:
    types: [ created ]
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependecies
        run: poetry install
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
       
      - name: Analysing the code with pylint
        run: poetry run pylint --fail-under=8 bring_order/
        
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        
      - name: Install pypa/build
        run: 
          poetry version $(git describe --tags --abbrev=0)
          python3 -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build --sdist --wheel --outdir dist/.
        
      - name: Publish distribution package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          
      - name: Publish distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
